name = "HiRepParsing"
uuid = "c7cc7de0-aa5c-4db3-979c-e9fc59cba489"
version = "0.1.0"
authors = ["Fabian Zierler <fabian.zierler@a1.net>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
ArgParse = "1.2.0"
CodecZstd = "0.8.7"
